export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';


export const FETCH_PlACES_INPROGRESS = "FETCH_PlACES_INPROGRESS";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_ERROR = "FETCH_PLACES_ERROR";
export const UPDATE_ADDED_PLACE ="UPDATE_ADDED_PLACE";



export const FETCH_TRIPS_INPROGRESS = "FETCH_TRIPS_INPROGRESS";
export const FETCH_TRIPS_SUCCESS = "FETCH_TRIPS_SUCCESS";
export const FETCH_TRIPS_ERROR = "FETCH_TRIPS_ERROR";